[package]
name = "com-gm112-rust-testlibrary"
version = "0.1.0"
edition = "2024"

#crate-type = ["cdylib", "rlib"] # cdylib for Wasm, rlib for Rust libraries

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.104"
