[package]
name = "com-gm112-rust-testlibrary"
version = "0.1.0"
edition = "2024"
rust-version = "1.90.0"

#crate-type = ["cdylib", "rlib"] # cdylib for Wasm, rlib for Rust libraries

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.104"
wasm-bindgen-test = "0.3.54"
