[toolchain]
channel = "1.90.0"
components = ["rustfmt", "clippy"]
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc", "aarch64-apple-darwin"] # see https://doc.rust-lang.org/nightly/rustc/platform-support.html
